Feat user info
VS-work/live-starter-api pull request #12
Opened 2017-12-27 16:44 UTC by DmitriyLitvinov

- changed responses for user requests

2017-12-28 10:13 UTC, Ugmaxie requested changes

2017-12-28 10:13 UTC, Ugmaxie commented on routes/user-signup.ts
> +  return newUser.save((err: Error, user: any): Function => {
avoid any

2017-12-28 10:13 UTC, Ugmaxie commented on routes/user-signup.ts
>  function getUserData(req: Request, res: any): Promise<any> | Function {
avoid any

2017-12-28 10:16 UTC, Ugmaxie requested changes

2017-12-28 10:16 UTC, Ugmaxie commented on routes/user-signup.ts
> +        return res.json({success: false, data: null, error: userCreateError});
why false?

2017-12-28 15:21 UTC, Ugmaxie requested changes

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +function getUserData(req: Request, res): Promise<any> | Function {
set type for res

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +    .exec((err: Error, user): Function => {
set type for user

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +function editUser(req: Request, res): Promise<any> | Function {
set type for res

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +function editUserAvatar(req: Request, res): Promise<any> | Function {
set type for res

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +function signUpUser(req: Request, res): Promise<any> {
set type for res

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +  return newUser.save((err: Error, user): Function => {
set type for user

2017-12-28 15:21 UTC, Ugmaxie commented on routes/user-signup.ts
> +function isEmailExist(req: Request, res): Promise<any> | Function {
set types for res

2017-12-29 10:40 UTC, Ugmaxie requested changes

2017-12-29 10:40 UTC, Ugmaxie commented on package.json
> +    "zone.js": "^0.8.11",
seems better to use strict versions of dependencies to avoid unexpected crashes which you can't handle

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
> +import { Request, Response, Express } from 'express';
try not to import whole module

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
> +function getUserData(req: Request, res: Response): void {
if !query.email function returns "undefined". Please use proper type for that.

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
> +    return;
return undefined

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
>    if (!body.email) {
the same as above

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
>    if (!body.email) {
the same as above

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
> +  newUser.save((err: Error, user: User) => {
type

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
> +    if (err) {
the same as above?

2017-12-29 10:40 UTC, Ugmaxie commented on routes/user-signup.ts
>    if (!body.email) {
the same as above

2017-12-29 11:49 UTC, DmitriyLitvinov commented on routes/user-signup.ts
> +import { Request, Response, Express } from 'express';
I didn't find another ways

2017-12-29 14:52 UTC, Ugmaxie requested changes

2017-12-29 14:52 UTC, Ugmaxie commented on routes/user-signup.ts
> +    .exec((err: Error): void => {
err =>

2017-12-29 14:52 UTC, Ugmaxie commented on routes/user-signup.ts
> +    .exec((dbError: Error, data: any): void => {
- no any
- if undefined is returned?

2017-12-29 15:29 UTC, Ugmaxie requested changes

2017-12-29 15:29 UTC, Ugmaxie commented on routes/user-signup.ts
> +    .exec((err: Error): void => {
err =>

2017-12-29 15:29 UTC, Ugmaxie commented on routes/user-signup.ts
> +  newUser.save((err: Error, user: User): void => {
: void | undefined

2017-12-29 15:39 UTC, Ugmaxie approved these changes

2017-12-29 15:39 UTC, merged