feat(parser for-cities) ready for test
VS-work/live-starter-api pull request #31
Opened 2018-04-03 14:28 UTC by DmitriyLitvinov

it is the parser for cities from JSON to DB

2018-04-03 15:42 UTC, Ugmaxie requested changes

2018-04-03 15:42 UTC, Ugmaxie commented on migration-db/parser-for-cities.ts
> +// const citiesList = require('./cities.json');
d'you need these comments?

2018-04-03 16:26 UTC, DmitriyLitvinov commented on migration-db/parser-for-cities.ts
> +// const citiesList = require('./cities.json');
yes, I need

2018-04-04 08:37 UTC, Ugmaxie approved these changes

2018-04-04 08:37 UTC, merged