Feat user profile update
VS-work/live-starter-api pull request #5
Opened 2017-02-15 08:39 UTC by Ugmaxie

2017-02-16 14:11 UTC, valorkin requested changes

2017-02-16 14:11 UTC, valorkin commented on package.json
> +    "start": "npm i && npm run tsc && ts-node app.ts",
remove `npm i` from here

2017-02-16 14:11 UTC, valorkin commented on package.json
> +    "tsc": "./node_modules/.bin/tsc --project tsconfig.json",
no need `./node_modules/.bin/` here
npm will use local versions only

2017-02-16 14:11 UTC, valorkin commented on package.json
> +    "flow.eslint": "./node_modules/.bin/eslint --ignore-path .gitignore --ext js --fix . .config",
fck eslint, you don't need it

2017-03-07 08:03 UTC, Betrozov approved these changes

2017-03-07 09:31 UTC, valorkin approved these changes

2017-03-07 09:36 UTC, merged